_extends: jellyfin-meta-plugins

template: |
  <!-- Optional: add a release summary here -->
  [Plugin build can be downloaded here](https://repo.jellyfin.org/releases/plugin/tv-maze/tv-maze_$NEXT_MAJOR_VERSION.0.0.0.zip).

  ## :sparkles: What's New

  $CHANGES
