name: "TVmaze"
guid: "A4A488D0-17A3-4919-8D82-7F3DE4F6B209"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvmaze.png"
version: "9"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Get TV metadata from TVmaze"
description: >
  Get TV metadata from TVmaze

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.TvMaze.dll"
  - "TvMaze.Api.Client.dll"
  - "Flurl.dll"
  - "Flurl.Http.dll"
  - "Polly.dll"
changelog: |2-
  ### Bug Fixes ###
  - tv-maze -> tvmaze in release-drafter config (#28) @oddstr13

  ### Code or Repo Maintenance ###
  - 10.8 support (#32) @crobibero
