---
name: "TV Maze"
guid: "A4A488D0-17A3-4919-8D82-7F3DE4F6B209"
version: "6.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
owner: "jellyfin"
overview: "Get TV metadata from TV Maze"
description: >
  Get TV metadata from TV Maze
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.TvMaze.dll"
- "TvMaze.Api.Client.dll"
- "Flurl.dll"
- "Flurl.Http.dll"
- "Polly.dll"
changelog: >
  Fix lookup by tvdb id
